name: Stream Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Buat symlink supaya Selenium bisa nemu google-chrome
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python3 scraper.py
