name: Scraper Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libasound2t64 chromium-browser

        # Symlink chromium ke google-chrome agar Selenium bisa mengenali
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Install Chromedriver v114
      run: |
        CHROMEDRIVER_VERSION=114.0.5735.90
        wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

        # Verifikasi versi
        google-chrome --version || chromium-browser --version
        chromedriver --version

    - name: Run scraper
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python3 scraper.py
