name: Scraping Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome & Chromedriver (v114 fallback)
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libasound2t64

        # Install Chrome stable
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

        # Install Chromedriver v114
        CHROMEDRIVER_VERSION=114.0.5735.90
        wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

        # Optional: verify installation
        google-chrome --version
        chromedriver --version

    - name: Run scraper
      run: |
        xvfb-run python scraper.py

    - name: Commit results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Update results [skip ci]" || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
