name: Update Token

on:
  schedule:
    - cron: "*/30 * * * *"  # Setiap 30 menit
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium selenium-wire
          sudo apt-get update
          sudo apt-get install -y chromium-driver
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Run scraper
        run: python token.py

      - name: Commit token
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add token.txt
          git commit -m "Update token"
          git push
