name: Run Python Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam (UTC)
  workflow_dispatch:     # Bisa dijalankan manual juga

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install blinker==1.7.0
          pip install selenium-wire webdriver-manager

      - name: Run script
        run: python script.py

      - name: Push changes to repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add latest.txt
          git commit -m "Update stream URL [auto]" || echo "No changes to commit"
          git push
